#run tripal instance with docker-compose

version: '3'
services: 

  web:
      build: .
      environment:
        DB_NAME: drupal
        DB_HOST: db
        DB_PORT: 5432
        PGUSER: postgres
        PGPASSWORD: example
      ports:
        - "8888:80"
      volumes:
        - druexp:/pgexp
      links: 
        - db

  db:
       image: postgres:9.6-alpine
       restart: always
       expose: 
        - "5432"
       environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: example 
         DB_PORT: 5432
       volumes:
         - druexp:/pgexp
         - pgdata:/var/lib/postgresql/data
         - ./db-init-scripts:/docker-entrypoint-initdb.d
  
  adminer:
      image: adminer
      restart: always
      ports:
        - "8080:8080"

volumes: 
  druexp: {}
  pgdata: {}
