#run tripal instance with docker-compose

version: '3'
services:

  drupal8_db:
    image: postgres:9.6-alpine
    restart: always
    expose:
    - "5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: drupal8_user

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d

  drupal8_web:
      build: .
      environment:
        DB_NAME: drupal
        DB_HOST: drupal8_db
        DB_PORT: 5432
        PGUSER: drupal8_user
        PGPASSWORD: example
      ports:
        - "8888:80"
      volumes:
        - webdir:/var/www/html


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata: {}
  webdir: {}
