version: "3.5"

services:
  nginx:
    image: nginx:latest
    ports:
      - "5002:80"
    volumes:
      - ./app:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
  app:
    build: '.'
    environment:
      # Default to a production environment unless specified by the user
      - "APP_ENV=${APP_ENV:-production}"
    volumes:
      - ./app:/code
  db:
    image: mariadb:10
    restart: always
    environment:
      # Don't forget to edit these variable for production
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  default:
    external:
      name: tripal-kong

volumes:
  dbdata:
